/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#12121d',
        'surface-dim': '#12121d',
        'surface-bright': '#383844',
        'surface-container-lowest': '#0d0d18',
        'surface-container-low': '#1b1a26',
        'surface-container': '#1f1f2a',
        'surface-container-high': '#292935',
        'surface-container-highest': '#343440',
        'surface-variant': '#343440',
        'on-surface': '#e3e0f1',
        'on-surface-variant': '#e8bcb8',
        'on-background': '#e3e0f1',
        'background': '#12121d',
        'primary': '#ffb4ac',
        'primary-container': '#e40e20',
        'primary-fixed': '#ffdad6',
        'primary-fixed-dim': '#ffb4ac',
        'on-primary': '#690007',
        'on-primary-container': '#fff7f6',
        'on-primary-fixed': '#410003',
        'on-primary-fixed-variant': '#93000e',
        'secondary': '#ffb4ac',
        'secondary-container': '#8d1416',
        'secondary-fixed': '#ffdad6',
        'secondary-fixed-dim': '#ffb4ac',
        'on-secondary': '#690007',
        'on-secondary-container': '#ff9990',
        'on-secondary-fixed': '#410003',
        'on-secondary-fixed-variant': '#8d1416',
        'tertiary': '#9acbff',
        'tertiary-container': '#0077bf',
        'tertiary-fixed': '#d0e4ff',
        'tertiary-fixed-dim': '#9acbff',
        'on-tertiary': '#003355',
        'on-tertiary-container': '#f7f9ff',
        'on-tertiary-fixed': '#001d34',
        'on-tertiary-fixed-variant': '#004a79',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'outline': '#ae8783',
        'outline-variant': '#5e3f3c',
        'inverse-surface': '#e3e0f1',
        'inverse-on-surface': '#302f3b',
        'inverse-primary': '#c00016',
        'surface-tint': '#ffb4ac',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Epilogue', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
